In [19]:
import pandas as pd


df = pd.read_excel('../datasets/bitcoin/bitcoin.xlsx', index_col='Date')

df

,Open,High,Low,Close,Volume,Market Cap
Date,,,,,,
"Feb 01, 2021",33114.58,34638.21,32384.23,33537.18,"61,400,400,660","624,349,044,409"
"Jan 31, 2021",34270.88,34288.33,32270.18,33114.36,"52,754,542,671","616,452,744,533"
"Jan 30, 2021",34295.94,34834.71,32940.19,34269.52,"65,141,828,798","637,924,573,284"
"Jan 29, 2021",34318.67,38406.26,32064.81,34316.39,"117,894,572,511","638,768,671,362"
"Jan 28, 2021",30441.04,31891.30,30023.21,31649.61,"78,948,162,368","589,083,045,078"
...,...,...,...,...,...,...
"May 03, 2013",106.25,108.13,79.10,97.75,0,"1,085,995,169"
"May 02, 2013",116.38,125.60,92.28,105.21,0,"1,168,517,495"
"May 01, 2013",139.00,139.89,107.72,116.99,0,"1,298,954,594"
"Apr 30, 2013",144.00,146.93,134.05,139.00,0,"1,542,813,125"
"Apr 29, 2013",134.44,147.49,134.00,144.54,0,"1,603,768,865"

In [20]:
def cal_change_rate(x):
    '''
    定义一个函数，计算当日股票价格的增长率。
    '''
    return (x['Close'] - x['Open']) / x['Open']

In [21]:
#使用自定义函数，操作数据框。
df.apply(cal_change_rate, axis=1).sort_values()

Date
Mar 12, 2020   -0.371869
Dec 18, 2013   -0.229283
Jan 14, 2015   -0.204520
Dec 06, 2013   -0.204273
Dec 16, 2013   -0.198062
                  ...
Nov 21, 2013    0.215557
Jul 20, 2017    0.241294
Dec 07, 2017    0.254702
Dec 19, 2013    0.333102
Nov 18, 2013    0.416811
Length: 2836, dtype: float64